### ISSUE TITLE
`sourmash taxonomy annotate` produces AttributeError: module 'sourmash.cli' has no attribute 'taxonomy'

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#2351] opened 2022-10-28 14:37 UTC
```
sourmash taxonomy annotate -g ../tests/testthat/test1.v450.gather.csv -t ~/github/2022-prjna853785-sourmash/inputs/sourmash_databases/genbank-2022.03-*gz

== This is sourmash version 4.5.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Traceback (most recent call last):
  File "/Users/taylorreiter/miniconda3/envs/sandbox/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/Users/taylorreiter/miniconda3/envs/sandbox/lib/python3.10/site-packages/sourmash/__main__.py", line 7, in main
    mod = getattr(sourmash.cli, args.cmd)
AttributeError: module 'sourmash.cli' has no attribute 'taxonomy'
```

but `sourmash tax annotate` works and `sourmash taxonomy -h` works

I don't spot any typos on my part so i think something got dropped here

**Comment by ctb** [comment] 2022-10-29 00:02
huh! can't replicate with latest branch OR with v4.5.0 checkout, and my v4.5.0 clean conda install doesn't replicate 🤔

**Comment by taylorreiter** [comment] 2022-11-01 12:09
well that's weird but also great. maybe i had a sneaky special character or something.

**Comment by ctb** [comment] 2022-11-14 13:39
can't reproduce :(. Closing for now! But thank you for reporting, I will keep an eye out!

**Closed as completed by ctb** 2022-11-14 13:39 UTC
