### ISSUE TITLE
Multisearch Threshold and Output Matches

### ISSUE THREAD

**Issue by agombolay** [sourmash-bio/sourmash#3284] opened 2024-08-10 17:59 UTC
When I run `multisearch`, using the code shown below, the number of output matches varies depending on the sample (for example, 0 matches, 760 matches, and 165 matches). It is my understanding that the default threshold value for `search` is 0.08 and the default number of output matches for `search` is 3. Is this correct? However, these default values do not seem to apply to `multisearch`. What are the default values for threshold and number of matches for `multisearch`? And is the threshold based on jaccard or containment?

`sourmash scripts multisearch sample.sig gtdb-rs214-k31.zip -o sample.csv`

Also, if the threshold for `multisearch` is set to 0, is `multisearch` supposed to output the results for all signatures in the reference database? For example, if I use the gtdb-rs214-k31.zip reference database (which contains 392,058 reference signatures) with `multisearch` and set the threshold to 0, should `multisearch` output the results for all 392,058 signatures? I ran `multisearch` with the threshold set to 0 and it output results for only 38,067 signatures rather than 392,058.

**Comment by ctb** [comment] 2024-08-11 23:28
Great questions!!

Yes, `search` is very old (it's one of the original three or four commands) and has aged badly; in part this is because it's one of the few commands left where we support regular MinHash and not just FracMinHash. There are some ideas for how to evolve it in #2002 but that's not happening soon b/c we like to keep old things working unless there's a strong reason not to.

It's gotten to the point where a variety of nifty new commands have come along and been iterated on and improved - prefetch, and the various things in the [`containment` plugin](https://github.com/sourmash-bio/sourmash_plugin_containment_search/) and now, finally, we have a fully-fleshed out `manysearch` (as of yesterday's release of the `sourmash_plugin_branchwater` v0.9.6 on conda-forge) and a separate `multisearch` command for multithreaded search (as well as `pairwise`, which just runs `multisearch` queries against themselves).

So, to finally answer your questions:

1. for `multisearch` the default threshold is 0.01, and it's for the containment of the query in the target; so you could conceivably see `A in B` reported but not `B in A`.

2. If threshold is set to 0, then any comparison for which there is a non-zero overlap is reported - so 0 doesn't mean display _everything_, but rather display everything for which at least one shared hash is available.

Related issues if you want to delve:
* update search muchly? https://github.com/sourmash-bio/sourmash/issues/2002
* `-n` and `--threshold` work together poorly... https://github.com/sourmash-bio/sourmash/issues/2169

HTH! Please ask away!

**Comment by agombolay** [comment] 2024-08-12 15:05
Thank you very much for clarifying this! 
I ran both `search` and `multisearch` on the same sample with threshold set to 0 and `search` output 36,511 matches and `multisearch` output 38,067 matches. Is the difference in the number of matches output by `search` and `multisearch` due to `search` using MinHash and `multisearch` using FracMinHash?

**Comment by ctb** [comment] 2024-08-12 15:26
that shouldn't be happening! I have one theory to do with duplicate sketches (genomes that are identical at the scaled resolution we are using). I'm happy to dig into the results files if you want to share them (via e-mail is fine) but if you are up to it, I would check to see if the md5sum column in the multisearch output has only 36,511 distinct md5sum values.

To be explicit: my guess is that `search` is collapsing identical sketches and only reporting one result per distinct sketch while multisearch is reporting one result per matching database entry. The latter behavior is IMO better because it reports all matching names, while the former behavior will let you know that there's at least one match, but not report all of the matches.

I will also look into it myself with a smaller test set to verify that that is what is happening.

Thanks again for reporting!

**Comment by agombolay** [comment] 2024-08-13 14:52
Thanks for letting me know, I will share the data via email.

**Comment by ctb** [comment] 2024-08-15 15:40
thanks for sending me the sketch in question - I have been able to reproduce your results 🎉
```
% wc -l *.csv
   38067 MNTN081_S144_multi_t0.csv
   36511 MNTN081_S144_search_t0.csv
```
will dig into what's going on now!

I wanted to note the time/memory comparison (details below) -

multisearch: 1m 53s, 24.6 GB of RAM
search: 18m 49s, 16.4 GB of RAM

Details:

```
        Command being timed: "sourmash scripts multisearch -t 0 MNTN081_S144.sig
 gtdb-rs214-k31.zip -o MNTN081_S144_multi_t0.csv"
        User time (seconds): 1706.75
        System time (seconds): 12.87
        Percent of CPU this job got: 1518%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:53.24
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 24593744
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 20
        Minor (reclaiming a frame) page faults: 3906842
        Voluntary context switches: 49465
        Involuntary context switches: 41196
        Swaps: 0
        File system inputs: 2360
        File system outputs: 16464

        Command being timed: "sourmash search -t 0 MNTN081_S144.sig gtdb-rs214-k
31.zip -o MNTN081_S144_search_t0.csv"
        User time (seconds): 1116.28
        System time (seconds): 14.35
        Percent of CPU this job got: 100%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 18:49.42
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 16368080
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 95765
        Minor (reclaiming a frame) page faults: 3439203
        Voluntary context switches: 3034
        Involuntary context switches: 1509
        Swaps: 0
        File system inputs: 24514784
        File system outputs: 23896
        Socket messages sent: 0
        Socket messages received: 0
```

**Comment by agombolay** [comment] 2024-08-15 17:01
Ok, great! Thanks for keeping me updated.

**Comment by ctb** [comment] 2024-08-16 13:06
using the following code,
```python
#! /usr/bin/env python
import pprint
import csv

search_rows = list(csv.DictReader(open('MNTN081_S144_search_t0.csv')))
msearch_rows = list(csv.DictReader(open('MNTN081_S144_multi_t0.csv')))

print("number of results")
print(f"{len(search_rows)}, {len(msearch_rows)}")

print("columns:")
print(list(search_rows[0].keys()))
print(list(msearch_rows[0].keys()))

print("number of queries (should be 1)")
print(set([ x['query_name'] for x in search_rows ]))
print(set([ x['query_name'] for x in msearch_rows ]))

a = set([ x['name'] for x in search_rows ])
b = set([ x['match_name'] for x in msearch_rows ])

print("number of matches:")
print(len(a), len(b))

print("in search only:")
print(len(a - b))
print("in msearch only:")
print(len(b - a))

print("md5:")
aa = set([ x['md5'] for x in search_rows ])
bb = set([ x['match_md5'] for x in msearch_rows ])


print("number of distinct matches:")
print(len(aa), len(bb))                     

print("in search only:")
print(len(aa - bb))
print("in msearch only:")
print(len(bb - aa))
```
I get:
```
number of results
36510, 38066
columns:
['similarity', 'md5', 'filename', 'name', 'query_filename', 'query_name', 'query_md5', 'ani']
['query_name', 'query_md5', 'match_name', 'match_md5', 'containment', 'max_containment', 'jaccard', 'intersect_hashes']
number of queries (should be 1)
{'MNTN081_S144'}
{'MNTN081_S144'}
number of matches:
36510 38066
in search only:
0
in msearch only:
1556
md5:
number of distinct matches:
36510 36510
in search only:
0
in msearch only:
0
outputting msearch only to 'msearch-only.csv'
```
so it looks like `search` is indeed collapsing matches with identical md5sums. The multisearch approach (NOT collapsing identical matches) is correct, IMO, but I think that's a relatively recent realization.

And hey, this was reported by someone else, too! https://github.com/sourmash-bio/sourmash/issues/2805

I'll discuss it more over there - and I'll close this issue unless you have additional questions!

**Comment by ctb** [comment] 2024-08-16 13:19
(please do let me know your desired resolution - do you need this behavior corrected in `search`? Or is it enough that we understand it for now? :)

**Comment by agombolay** [comment] 2024-08-16 13:42
Thank you very much for taking the time to look into this! For my team and I, I think the `multisearch` option is best mainly since it is the much faster option. I do have a question about identical md5sums. Why would some matches have identical md5sums? Are there some genome matches in the database that have identical md5sums? Are md5sums not unique to each genome?

**Comment by ctb** [comment] 2024-08-16 13:51
> Why would some matches have identical md5sums? Are there some genome matches in the database that have identical md5sums? Are md5sums not unique to each genome?

They're unique to the sketched collections of k-mers - so, at the resolution of the `scaled` value chosen, these genomes are identical.

**Comment by ctb** [comment] 2024-08-16 13:51
I'll close for now - ask as you have more questions!

**Closed as completed by ctb** 2024-08-16 13:51 UTC

**Comment by agombolay** [comment] 2024-08-16 13:54
Ok, that make sense to me! Thanks again!
